spring.application.name=PaymentService

server.port=${PAYMENT_SERVICE_PORT}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.value=${RAZORPAY_KEY_VALUE}

stripe.secret.key=${STRIPE_SECRET_KEY}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
